# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RDniLqLic4MMRgOdVMo9PIRrFPK-iNq
"""

# PySpark Analysis of E-Commerce Behavior Data
# Designed to run on Google Cloud Platform (GCP) using Dataproc

from pyspark.sql import SparkSession

# Initialize Spark session
spark = SparkSession.builder.appName("EcommerceAnalysis").getOrCreate()

# 1. Read dataset from Google Cloud Storage (GCS)
df = spark.read.csv("gs://ecommerce-data-bucket-test/2019-Oct.csv", header=True, inferSchema=True)

# 2. Display schema (column structure and types)
df.printSchema()

# 3. Show the first 5 rows of the dataset
df.show(5)

# 4. Remove rows with any missing (null) values
df_clean = df.na.drop()

# 5. Print number of remaining rows after cleaning
print("Remaining rows after removing nulls:", df_clean.count())

# 6. Register cleaned DataFrame as a temporary SQL view
df_clean.createOrReplaceTempView("ecommerce_cleaned")

# 7. Count of each event type (view, cart, purchase, etc.)
spark.sql("""
    SELECT event_type, COUNT(*) as total
    FROM ecommerce_cleaned
    GROUP BY event_type
""").show()

# 8. Number of user actions per hour (activity distribution over time)
spark.sql("""
    SELECT hour(event_time) AS hour_of_day, COUNT(*) AS total_events
    FROM ecommerce_cleaned
    GROUP BY hour_of_day
    ORDER BY hour_of_day
""").show(24)

# 9. Most viewed products
spark.sql("""
    SELECT product_id, COUNT(*) as views
    FROM ecommerce_cleaned
    WHERE event_type = 'view'
    GROUP BY product_id
    ORDER BY views DESC
    LIMIT 10
""").show()

# 10. Most purchased products
spark.sql("""
    SELECT product_id, COUNT(*) as purchases
    FROM ecommerce_cleaned
    WHERE event_type = 'purchase'
    GROUP BY product_id
    ORDER BY purchases DESC
    LIMIT 10
""").show()

# 11. Most popular brands based on event frequency
spark.sql("""
    SELECT brand, COUNT(*) as total_events
    FROM ecommerce_cleaned
    WHERE brand IS NOT NULL
    GROUP BY brand
    ORDER BY total_events DESC
    LIMIT 10
""").show()

# 12. Top-selling product categories
spark.sql("""
    SELECT category_code, COUNT(*) as purchases
    FROM ecommerce_cleaned
    WHERE event_type = 'purchase' AND category_code IS NOT NULL
    GROUP BY category_code
    ORDER BY purchases DESC
    LIMIT 10
""").show()